### ISSUE TITLE
Ansible Module currently not working with Python3

### ISSUE THREAD

**Issue by quater** [pjodouin/ansible-boto3#4]
When running Ansible with Python3, the below error is encountered.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'basestring' is not defined
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_tb8bnh1w/ansible_module_aws.py", line 345, in <module>
        main()
      File "/tmp/ansible_tb8bnh1w/ansible_module_aws.py", line 319, in main
        params = fix_input(module.params['params'], module.params['convert_to_integer'], key_case)
      File "/tmp/ansible_tb8bnh1w/ansible_module_aws.py", line 245, in fix_input
        for item in node.keys() if not (isinstance(node[item], basestring) and node[item].startswith('__omit_'))
      File "/tmp/ansible_tb8bnh1w/ansible_module_aws.py", line 245, in <listcomp>
        for item in node.keys() if not (isinstance(node[item], basestring) and node[item].startswith('__omit_'))
    NameError: name 'basestring' is not defined
  module_stdout: ''
  msg: MODULE FAILURE
  rc: 1
```

**Comment by quater** [comment]
Added this https://github.com/pjodouin/ansible-boto3/pull/5 PR to fix this.
